//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload
    {
        public int id { get; set; }
        public string path { get; set; }
    }
}
